# SPDX-License-Identifier: Apache-2.0

name: Mlkem
type: kem
implementations:
  - name: mlkem512
    claimed-nist-level: 1
    claimed-security: IND-CCA2
    length-public-key: 800
    length-ciphertext: 768
    length-secret-key: 1632
    length-shared-secret: 32
    nistkat-sha256: 4b88ac7643ff60209af1175e025f354272e88df827a0ce1c056e403629b88e04
  - name: mlkem768
    claimed-nist-level: 3
    claimed-security: IND-CCA2
    length-public-key: 1184
    length-ciphertext: 1088
    length-secret-key: 2400
    length-shared-secret: 32
    nistkat-sha256: 21b4a1e1ea34a13c26a9da5eeb9325afb5ca11596ca6f3704c3f2637e3ea7524
  - name: mlkem1024
    claimed-nist-level: 5
    claimed-security: IND-CCA2
    length-public-key: 1568
    length-ciphertext: 1568
    length-secret-key: 3168
    length-shared-secret: 32
    nistkat-sha256: 6471398b0a728ee1ef39e93bb89b526fbf59587a3662edadbcfc6c88a512cd71
