#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

# consts
ROOT="$(realpath "$(dirname "$0")"/../../)"

checkerr()
{
  if [[ $? == 127 ]]; then
    SUCCESS=false
    return
  fi

  if [[ ${#1} != 0 ]]; then
    echo "$1" | while read -r file line; do
      echo "::error file={$file},line={${line:-1}},title={Format error}::$file require to be formatted"
    done
    SUCCESS=false
  fi
}

# Formatting
SUCCESS=true

echo "::group::Linting nix files with nixpkgs-fmt"
checkerr "$(nixpkgs-fmt --check "$ROOT")"
echo "::endgroup::"

echo "::group::Linting shell scripts with shfmt"
checkerr "$(shfmt -s -l -i 2 -ci -fn $(shfmt -f $(git grep -l '' :/)))"
echo "::endgroup::"

echo "::group::Linting c files with astyle"
checkerr "$(astyle $(git ls-files ":/*.c" ":/*.h") --options="$ROOT/.astylerc" --dry-run --formatted | awk '{print $2}')"
echo "::endgroup::"

#
if ! $SUCCESS; then
  exit 1
fi
